<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.github.openjverein</groupId>
  <artifactId>jverein-parent</artifactId>
  <version>3.2.0</version>
  <packaging>pom</packaging>

  <modules>
    <module>jameica-build</module>
    <module>hibiscus-build</module>
    <module>jverein</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>11</maven.compiler.release>
    <jameica.version>2.12.0</jameica.version>
    <hibiscus.version>2.12.2</hibiscus.version>
    <build.cache.dir>${maven.multiModuleProjectDirectory}/.build-cache</build.cache.dir>

    <maven.antrun.plugin.version>3.1.0</maven.antrun.plugin.version>
    <maven.compiler.plugin.version>3.14.1</maven.compiler.plugin.version>
    <maven.surefire.plugin.version>3.5.4</maven.surefire.plugin.version>
  </properties>
</project>
