# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: OpenJVerein build check

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
    paths:
      - 'plugin.xml'
      - 'build/**'
      - 'lib/**'
      - 'lib.src/**'
      - 'src/**'
  push:
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build.yml

  build-check:
    needs: call-reusable-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openjverein
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: cache-{{ hashFiles('setup-build.xml') }}-{{ hashFiles('**/pom.xml') }}
          restore-keys: |
            cache-{{ hashFiles('setup-build.xml') }}-
            cache-

      - name: Build openjverein plugin
        run: mvn --batch-mode --file pom.xml clean package

      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository
          key: cache-{{ hashFiles('setup-build.xml') }}-{{ hashFiles('**/pom.xml') }}
